name: CI - Main

on:
  push:
    branches-ignore:
      - 'skip-ci-*'
      - 'DEFEDIT-*'
      - 'editor-dev'

  repository_dispatch: {}

jobs:
  # ---- BUILD ENGINE VERSIONS ------------------
  bld-eng-darwin:
    strategy:
      matrix:
        platform: [arm64-macos]
    runs-on: macos-14
    timeout-minutes: 30
    steps: [
      { name: 'Checkout', uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11, with: { ref: '${{env.BUILD_BRANCH}}' } },
      { name: 'Install Python', uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c, with: { python-version: 3.13} },
      { name: 'XCode', uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd, with: { xcode-version: '16.2' } },
      { name: 'Install Java', uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9, with: { java-version: '25', distribution: 'temurin'} },
      { name: 'Install CMake', uses: lukka/get-cmake@v4.1.1 },
      {
        name: 'Setup dotnet',
        shell: bash,
        run: 'curl -O https://dot.net/v1/dotnet-install.sh &&
              chmod +x ./dotnet-install.sh &&
              export NUGET_PACKAGES=$(pwd)/tmp/dynamo_home/ext/share/nuget &&
              export DOTNET_ROOT=$(pwd)/tmp/dynamo_home/ext/bin/dotnet &&
              echo "NUGET_PACKAGES=${NUGET_PACKAGES}" >> $GITHUB_ENV &&
              echo "DOTNET_CLI_HOME=${DOTNET_ROOT}" >> $GITHUB_ENV &&
              echo "DOTNET_CLI_TELEMETRY_OPTOUT=1" >> $GITHUB_ENV &&
              mkdir -p ${DOTNET_ROOT} &&
              mkdir -p ${NUGET_PACKAGES} &&
              ./dotnet-install.sh --channel 9.0.1xx --install-dir ${DOTNET_ROOT} &&
              echo ${DOTNET_ROOT} >> $GITHUB_PATH &&
              echo "dotnet version: $(dotnet --version)"'
      },
      { name: 'Install dependencies', shell: bash, run: 'ci/ci.sh install --platform=${{ matrix.platform }}' },
      { name: 'Show installed .NET SDKs', run: 'dotnet --list-sdks' },
      { name: 'Show installed .NET runtimes', run: 'dotnet --list-runtimes' },
      {
        name: 'Build engine',
        if: (github.event_name != 'repository_dispatch') || ((github.event_name == 'repository_dispatch') && (github.event.client_payload.skip_engine != true)),
        run: 'ci/ci.sh --platform=${{ matrix.platform }} --archive --skip-builtins --skip-docs engine'
      }]

 